export const destinations = [
    "Colombia, Bogotá",
    "Colombia, Medellín",
    "Colombia, Cartagena",
    "Colombia, Cali",
    "Colombia, Santa Marta",
    "Colombia, San Andrés",
    "Colombia, Barranquilla",
    "Colombia, Pereira",
    "Colombia, Bucaramanga",
    "Colombia, Manizales",
    "Mexico, Ciudad de México",
    "Mexico, Cancún",
    "Mexico, Guadalajara",
    "Mexico, Monterrey",
    "Mexico, Tulum",
    "Argentina, Buenos Aires",
    "Argentina, Mendoza",
    "Argentina, Córdoba",
    "Peru, Lima",
    "Peru, Cusco",
    "Chile, Santiago",
    "Brasil, Rio de Janeiro",
    "Brasil, Sao Paulo",
    "Estados Unidos, Miami",
    "Estados Unidos, Nueva York",
    "Estados Unidos, Orlando",
    "España, Madrid",
    "España, Barcelona",
];
