// Common origin cities with airport codes
export const originCities = [
  "BOG - Bogotá",
  "MDE - Medellín",
  "CTG - Cartagena",
  "CLO - Cali",
  "BAQ - Barranquilla",
  "ADZ - San Andrés",
  "SMR - Santa Marta",
  "PEI - Pereira",
  "BGA - Bucaramanga",
  "MZL - Manizales",
  "MEX - Ciudad de México",
  "CUN - Cancún",
  "GDL - Guadalajara",
  "MTY - Monterrey",
  "EZE - Buenos Aires",
  "LIM - Lima",
  "CUZ - Cusco",
  "SCL - Santiago",
  "GIG - Rio de Janeiro",
  "GRU - Sao Paulo",
  "MIA - Miami",
  "JFK - Nueva York",
  "MCO - Orlando",
  "MAD - Madrid",
  "BCN - Barcelona",
];

